# Generated by Django 5.1.1 on 2024-10-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0003_alter_course_teacher'),
        ('Student', '0005_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='info_students',
            field=models.ManyToManyField(related_name='courses', to='Student.student'),
        ),
    ]
