# Generated by Django 5.1.1 on 2024-09-25 21:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, default='No address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1', 'Grado Primero'), ('2', 'Grado Segundo'), ('3', 'Grado Tercero'), ('4', 'Grado Cuarto'), ('5', 'Grado Quinto'), ('6', 'Grado Sexto'), ('7', 'Grado Séptimo'), ('8', 'Grado Octavo'), ('9', 'Grado Noveno'), ('10', 'Grado Décimo'), ('11', 'Grado Once')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to='Users.customuser'),
        ),
    ]
