# Generated by Django 5.1.1 on 2024-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_student_gender_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('1', 'Grado Primero'), ('2', 'Grado Segundo'), ('3', 'Grado Tercero'), ('4', 'Grado Cuarto'), ('5', 'Grado Quinto'), ('6', 'Grado Sexto'), ('7', 'Grado Séptimo'), ('8', 'Grado Octavo'), ('9', 'Grado Noveno'), ('10', 'Grado Décimo'), ('11', 'Grado Once')], max_length=2),
        ),
    ]
