# Generated by Django 5.1.1 on 2024-09-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_alter_student_user'),
        ('Teachers', '0003_alter_teacher_user'),
        ('Users', '0002_user_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
